# Generated by Django 5.0.14 on 2026-02-23 09:53

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtaildocs', '0014_alter_document_file_size'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='Résumé')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('cta', 7), ('faq', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citation'}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary')], 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5), ('style', 6)]], {'label': 'CTA'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('question', 8), ('answer', 9)]], {'label': 'FAQ'})})),
                ('author_name', models.CharField(blank=True, max_length=120, verbose_name='Auteur')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Date de publication')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SpeciesPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='Résumé')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('cta', 7), ('faq', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citation'}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary')], 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5), ('style', 6)]], {'label': 'CTA'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('question', 8), ('answer', 9)]], {'label': 'FAQ'})})),
                ('species', models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='volailles', max_length=24, verbose_name='Espèce')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='Résumé')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('cta', 7), ('faq', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citation'}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary')], 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5), ('style', 6)]], {'label': 'CTA'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('question', 8), ('answer', 9)]], {'label': 'FAQ'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='Résumé')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('cta', 7), ('faq', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citation'}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary')], 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5), ('style', 6)]], {'label': 'CTA'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('question', 8), ('answer', 9)]], {'label': 'FAQ'})})),
                ('hero_title', models.CharField(blank=True, max_length=200, verbose_name='Titre hero')),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Sous-titre hero')),
                ('cta_label', models.CharField(blank=True, max_length=80, verbose_name='Label CTA')),
                ('cta_url', models.URLField(blank=True, verbose_name='URL CTA')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PartnerPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='Résumé')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('cta', 7), ('faq', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citation'}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary')], 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5), ('style', 6)]], {'label': 'CTA'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('question', 8), ('answer', 9)]], {'label': 'FAQ'})})),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='Résumé')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('cta', 7), ('faq', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citation'}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary')], 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5), ('style', 6)]], {'label': 'CTA'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('question', 8), ('answer', 9)]], {'label': 'FAQ'})})),
                ('product_category', models.CharField(blank=True, max_length=120, verbose_name='Catégorie')),
                ('stage', models.CharField(blank=True, max_length=120, verbose_name='Stade')),
                ('benefits', wagtail.fields.StreamField([('benefit', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Bénéfice'})})),
                ('datasheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResourcePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='Résumé')),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('cta', 7), ('faq', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Titre', 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'label': 'Texte'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'label': 'Citation'}), 4: ('wagtail.blocks.CharBlock', (), {'required': True}), 5: ('wagtail.blocks.URLBlock', (), {'required': True}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('primary', 'Primary'), ('secondary', 'Secondary')], 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('label', 4), ('url', 5), ('style', 6)]], {'label': 'CTA'}), 8: ('wagtail.blocks.CharBlock', (), {}), 9: ('wagtail.blocks.RichTextBlock', (), {}), 10: ('wagtail.blocks.StructBlock', [[('question', 8), ('answer', 9)]], {'label': 'FAQ'})})),
                ('resource_type', models.CharField(blank=True, max_length=120, verbose_name='Type de ressource')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='MARIDAV CI', max_length=120, verbose_name='Nom société')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('footer_note', models.CharField(blank=True, max_length=255, verbose_name='Note de bas de page')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Paramètres site',
            },
        ),
    ]
