# Generated by Django 5.0.14 on 2026-01-05 14:39

import crm.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Code client')),
                ('customer_type', models.CharField(choices=[('eleveur', 'Éleveur'), ('distributeur', 'Distributeur'), ('integrateur', 'Intégrateur'), ('veterinaire', 'Vétérinaire'), ('revendeur', 'Revendeur'), ('industrie', 'Industrie/Transformateur'), ('autre', 'Autre')], default='eleveur', max_length=32, verbose_name='Type de client')),
                ('segment', models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='volailles', max_length=24, verbose_name='Espèce principale')),
                ('size', models.CharField(blank=True, max_length=120, verbose_name='Taille/Capacité')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ville')),
                ('region', models.CharField(blank=True, choices=[('Abidjan', 'Abidjan'), ('Bouaké', 'Bouaké'), ('Yamoussoukro', 'Yamoussoukro'), ('San-Pédro', 'San-Pédro'), ('Korhogo', 'Korhogo'), ('Daloa', 'Daloa'), ('Man', 'Man'), ('Gagnoa', 'Gagnoa'), ('Autre', 'Autre')], max_length=120, verbose_name='Région')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('country', models.CharField(default="Côte d'Ivoire", max_length=80)),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('prospect', 'Prospect'), ('actif', 'Actif'), ('dormant', 'Dormant')], default='prospect', max_length=24)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='Référence')),
                ('packaging', models.CharField(blank=True, max_length=120, verbose_name='Conditionnement')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=24)),
                ('usage_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('segment', models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='multi', max_length=24)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('whatsapp', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_channel', models.CharField(choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visite', 'Visite terrain'), ('site', 'Site web'), ('referent', 'Référent/Partenaire')], default='whatsapp', max_length=24)),
                ('is_primary', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.customer')),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom du contact')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Structure')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('channel', models.CharField(choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visite', 'Visite terrain'), ('site', 'Site web'), ('referent', 'Référent/Partenaire')], default='site', max_length=24)),
                ('segment', models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='volailles', max_length=24)),
                ('need_type', models.CharField(choices=[('aliments', 'Aliments complets'), ('additifs', 'Additifs/Correcteurs'), ('biosecurite', 'Biosécurité'), ('formation', 'Formation/Atelier'), ('logistique', 'Logistique/Disponibilité')], default='aliments', max_length=32, verbose_name='Besoin')),
                ('expected_volume', models.CharField(blank=True, max_length=120, verbose_name='Volume/Capacité')),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('contacte', 'Contacté'), ('qualifie', 'Qualifié'), ('proposition', 'Proposition'), ('perdu', 'Perdu'), ('converti', 'Converti')], default='nouveau', max_length=24)),
                ('next_step_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('stage', models.CharField(choices=[('diagnostic', 'Diagnostic'), ('offre', 'Offre/Devis'), ('negociation', 'Négociation'), ('gagne', 'Gagné'), ('perdu', 'Perdu')], default='diagnostic', max_length=24)),
                ('expected_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('probability', models.PositiveIntegerField(default=30)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('segment', models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='volailles', max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.lead')),
            ],
            options={
                'ordering': ['expected_close_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(default=crm.models.default_order_number, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('devis', 'Devis'), ('confirme', 'Confirmé'), ('livre', 'Livré'), ('annule', 'Annulé')], default='brouillon', max_length=16)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('billing_contact', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.product')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm.productcategory'),
        ),
        migrations.CreateModel(
            name='SupportCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(default=crm.models.default_support_ref, max_length=32, unique=True)),
                ('case_type', models.CharField(choices=[('visite_technique', 'Visite technique'), ('biosecurite', 'Biosécurité'), ('qualite', 'Réclamation qualité'), ('formation', 'Formation'), ('logistique', 'Logistique/Stock')], default='visite_technique', max_length=24)),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('en_attente', 'En attente client'), ('cloture', 'Clôturé')], default='ouvert', max_length=24)),
                ('priority', models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute')], default='normale', max_length=16)),
                ('species', models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='volailles', max_length=24)),
                ('description', models.TextField()),
                ('channel', models.CharField(choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visite', 'Visite terrain'), ('site', 'Site web'), ('referent', 'Référent/Partenaire')], default='whatsapp', max_length=24)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to='crm.contact')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_cases', to='crm.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=24)),
                ('activity_type', models.CharField(choices=[('appel', 'Appel'), ('visite', 'Visite'), ('email', 'E-mail'), ('relance', 'Relance'), ('devis', 'Devis'), ('livraison', 'Livraison'), ('formation', 'Formation')], default='appel', max_length=24)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.lead')),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.opportunity')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.order')),
                ('support_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.supportcase')),
            ],
            options={
                'ordering': ['status', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_date', models.DateField(default=django.utils.timezone.now)),
                ('species', models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='volailles', max_length=24)),
                ('purpose', models.CharField(choices=[('diagnostic', 'Diagnostic'), ('suivi', 'Suivi technique'), ('formation', 'Formation'), ('audit', 'Audit biosécurité')], default='diagnostic', max_length=32)),
                ('observations', models.TextField()),
                ('actions', models.TextField()),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('biosecurity_score', models.PositiveIntegerField(default=0)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='crm.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_reports', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='crm.customer')),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
