# Generated by Django 5.0.14 on 2026-01-05 15:01

import crm.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'permissions': [('view_dashboard', 'Peut voir le tableau de bord CRM'), ('view_reports', 'Peut consulter les rapports CRM'), ('manage_sales_team', "Peut gérer l'équipe commerciale")]},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='crm.customer', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='expected_close_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de clôture'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='expected_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valeur attendue'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='crm.lead', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='probability',
            field=models.PositiveIntegerField(default=30, verbose_name='Probabilité (%)'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='segment',
            field=models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='volailles', max_length=24, verbose_name='Espèce'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('diagnostic', 'Diagnostic'), ('offre', 'Offre/Devis'), ('negociation', 'Négociation'), ('gagne', 'Gagné'), ('perdu', 'Perdu')], default='diagnostic', max_length=24, verbose_name='Étape'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_contact',
            field=models.CharField(blank=True, max_length=255, verbose_name='Contact facturation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='crm.customer', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de livraison'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=crm.models.default_order_number, max_length=32, unique=True, verbose_name='Numéro de commande'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('devis', 'Devis'), ('confirme', 'Confirmé'), ('livre', 'Livré'), ('annule', 'Annulé')], default='brouillon', max_length=16, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.product', verbose_name='Produit'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantité'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm.productcategory', verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('actif', 'Actif'), ('archive', 'Archivé')], default='actif', max_length=24, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='product',
            name='usage_notes',
            field=models.TextField(blank=True, verbose_name="Notes d'usage"),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='segment',
            field=models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='multi', max_length=24, verbose_name='Espèce'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Code URL'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='case_type',
            field=models.CharField(choices=[('visite_technique', 'Visite technique'), ('biosecurite', 'Biosécurité'), ('qualite', 'Réclamation qualité'), ('formation', 'Formation'), ('logistique', 'Logistique/Stock')], default='visite_technique', max_length=24, verbose_name='Type de ticket'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='channel',
            field=models.CharField(choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visite', 'Visite terrain'), ('site', 'Site web'), ('referent', 'Référent/Partenaire')], default='whatsapp', max_length=24, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_cases', to='crm.contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_cases', to='crm.customer', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='priority',
            field=models.CharField(choices=[('basse', 'Basse'), ('normale', 'Normale'), ('haute', 'Haute')], default='normale', max_length=16, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='reference',
            field=models.CharField(default=crm.models.default_support_ref, max_length=32, unique=True, verbose_name='Référence'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='resolution',
            field=models.TextField(blank=True, verbose_name='Résolution'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='species',
            field=models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='volailles', max_length=24, verbose_name='Espèce'),
        ),
        migrations.AlterField(
            model_name='supportcase',
            name='status',
            field=models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('en_attente', 'En attente client'), ('cloture', 'Clôturé')], default='ouvert', max_length=24, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='task',
            name='activity_type',
            field=models.CharField(choices=[('appel', 'Appel'), ('visite', 'Visite'), ('email', 'E-mail'), ('relance', 'Relance'), ('devis', 'Devis'), ('livraison', 'Livraison'), ('formation', 'Formation')], default='appel', max_length=24, verbose_name="Type d'activité"),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='task',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.customer', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Échéance'),
        ),
        migrations.AlterField(
            model_name='task',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.lead', verbose_name='Lead'),
        ),
        migrations.AlterField(
            model_name='task',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.opportunity', verbose_name='Opportunité'),
        ),
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.order', verbose_name='Commande'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('termine', 'Terminé')], default='a_faire', max_length=24, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='task',
            name='support_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='crm.supportcase', verbose_name='Ticket support'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='actions',
            field=models.TextField(verbose_name='Actions'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='biosecurity_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Score biosécurité'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='crm.contact', verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_reports', to=settings.AUTH_USER_MODEL, verbose_name='Rédigé par'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='crm.customer', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de suivi'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='observations',
            field=models.TextField(verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='purpose',
            field=models.CharField(choices=[('diagnostic', 'Diagnostic'), ('suivi', 'Suivi technique'), ('formation', 'Formation'), ('audit', 'Audit biosécurité')], default='diagnostic', max_length=32, verbose_name='Objet'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='species',
            field=models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='volailles', max_length=24, verbose_name='Espèce'),
        ),
        migrations.AlterField(
            model_name='visitreport',
            name='visit_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date de visite'),
        ),
    ]
