# Generated by Django 5.0.14 on 2026-01-05 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customer_options_alter_opportunity_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.customer', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=120, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='Contact principal'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='preferred_channel',
            field=models.CharField(choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visite', 'Visite terrain'), ('site', 'Site web'), ('referent', 'Référent/Partenaire')], default='whatsapp', max_length=24, verbose_name='Canal préféré'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='role',
            field=models.CharField(blank=True, max_length=120, verbose_name='Fonction'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=40, verbose_name='WhatsApp'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='channel',
            field=models.CharField(choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visite', 'Visite terrain'), ('site', 'Site web'), ('referent', 'Référent/Partenaire')], default='site', max_length=24, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='next_step_date',
            field=models.DateField(blank=True, null=True, verbose_name='Prochaine action'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=40, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='segment',
            field=models.CharField(choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], default='volailles', max_length=24, verbose_name='Espèce'),
        ),
    ]
