# Generated by Django 5.0.14 on 2026-01-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_contact_customer_alter_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='expected_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Valeur attendue (FCFA)'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix unitaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix unitaire (FCFA)'),
        ),
    ]
