# Generated by Django 5.0.14 on 2026-02-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_opportunity_expected_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='lead',
            name='referrer',
            field=models.URLField(blank=True, verbose_name='Référent'),
        ),
        migrations.AddField(
            model_name='lead',
            name='source_page',
            field=models.URLField(blank=True, verbose_name='Page source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, verbose_name='User agent'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=120, verbose_name='UTM campaign'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_content',
            field=models.CharField(blank=True, max_length=120, verbose_name='UTM content'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=120, verbose_name='UTM medium'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, max_length=120, verbose_name='UTM source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_term',
            field=models.CharField(blank=True, max_length=120, verbose_name='UTM term'),
        ),
    ]
