# Generated by Django 5.0.14 on 2026-02-24 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_lead_ip_address_lead_referrer_lead_source_page_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interests',
            field=models.JSONField(blank=True, default=list, verbose_name='Intérêts'),
        ),
        migrations.AddField(
            model_name='lead',
            name='objective',
            field=models.CharField(blank=True, max_length=255, verbose_name='Objectif'),
        ),
        migrations.AddField(
            model_name='lead',
            name='preferred_channel',
            field=models.CharField(blank=True, choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visite', 'Visite terrain'), ('site', 'Site web'), ('referent', 'Référent/Partenaire')], max_length=24, verbose_name='Canal préféré'),
        ),
        migrations.AddField(
            model_name='lead',
            name='product_interest',
            field=models.CharField(blank=True, max_length=255, verbose_name='Produit/Gamme'),
        ),
        migrations.AddField(
            model_name='lead',
            name='region',
            field=models.CharField(blank=True, max_length=120, verbose_name='Région/Ville'),
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(blank=True, max_length=120, verbose_name='Stade/Objectif'),
        ),
        migrations.CreateModel(
            name='InboundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('lead', 'Lead web'), ('contact', 'Contact/Devis'), ('product', 'Produit'), ('career', 'Carrière'), ('newsletter', 'Newsletter')], max_length=24, verbose_name='Type')),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau'), ('a_qualifier', 'À qualifier'), ('assigne', 'Assigné'), ('converti', 'Converti'), ('cloture', 'Clôturé')], default='nouveau', max_length=24, verbose_name='Statut')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nom')),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Structure')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('segment', models.CharField(blank=True, choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], max_length=24, verbose_name='Espèce')),
                ('stage', models.CharField(blank=True, max_length=120, verbose_name='Stade/Objectif')),
                ('intent', models.CharField(blank=True, max_length=120, verbose_name='Intention')),
                ('channel_preference', models.CharField(blank=True, choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visite', 'Visite terrain'), ('site', 'Site web'), ('referent', 'Référent/Partenaire')], max_length=24, verbose_name='Canal préféré')),
                ('volume', models.CharField(blank=True, max_length=120, verbose_name='Volume/Capacité')),
                ('product', models.CharField(blank=True, max_length=255, verbose_name='Produit/Gamme')),
                ('objective', models.CharField(blank=True, max_length=255, verbose_name='Objectif')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Région/Ville')),
                ('preferred_time', models.CharField(blank=True, max_length=120, verbose_name='Créneau préféré')),
                ('interests', models.JSONField(blank=True, default=list, verbose_name='Intérêts')),
                ('consent', models.BooleanField(default=False, verbose_name='Consentement')),
                ('source_page', models.URLField(blank=True, verbose_name='Page source')),
                ('referrer', models.URLField(blank=True, verbose_name='Référent')),
                ('utm_source', models.CharField(blank=True, max_length=120, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=120, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=120, verbose_name='UTM campaign')),
                ('utm_content', models.CharField(blank=True, max_length=120, verbose_name='UTM content')),
                ('utm_term', models.CharField(blank=True, max_length=120, verbose_name='UTM term')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User agent')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Données brutes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_requests', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_requests', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='Nom & prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='Téléphone')),
                ('role', models.CharField(blank=True, max_length=120, verbose_name='Poste visé')),
                ('experience', models.CharField(blank=True, max_length=120, verbose_name='Expérience')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Ville de résidence')),
                ('availability', models.CharField(blank=True, max_length=120, verbose_name='Disponibilité')),
                ('mobility', models.CharField(blank=True, max_length=120, verbose_name='Mobilité')),
                ('message', models.TextField(blank=True, verbose_name='Motivations')),
                ('specialites', models.JSONField(blank=True, default=list, verbose_name='Spécialités')),
                ('cv', models.FileField(blank=True, null=True, upload_to='careers/', verbose_name='CV')),
                ('consent', models.BooleanField(default=False, verbose_name='Consentement')),
                ('status', models.CharField(choices=[('recu', 'Reçu'), ('etude', 'En étude'), ('entretien', 'Entretien'), ('refuse', 'Refusé'), ('retenu', 'Retenu')], default='recu', max_length=24, verbose_name='Statut')),
                ('source_page', models.URLField(blank=True, verbose_name='Page source')),
                ('referrer', models.URLField(blank=True, verbose_name='Référent')),
                ('utm_source', models.CharField(blank=True, max_length=120, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=120, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=120, verbose_name='UTM campaign')),
                ('utm_content', models.CharField(blank=True, max_length=120, verbose_name='UTM content')),
                ('utm_term', models.CharField(blank=True, max_length=120, verbose_name='UTM term')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User agent')),
                ('inbound_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_application', to='crm.inboundrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('desabonne', 'Désabonné')], default='actif', max_length=24, verbose_name='Statut')),
                ('source_page', models.URLField(blank=True, verbose_name='Page source')),
                ('referrer', models.URLField(blank=True, verbose_name='Référent')),
                ('utm_source', models.CharField(blank=True, max_length=120, verbose_name='UTM source')),
                ('utm_medium', models.CharField(blank=True, max_length=120, verbose_name='UTM medium')),
                ('utm_campaign', models.CharField(blank=True, max_length=120, verbose_name='UTM campaign')),
                ('utm_content', models.CharField(blank=True, max_length=120, verbose_name='UTM content')),
                ('utm_term', models.CharField(blank=True, max_length=120, verbose_name='UTM term')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User agent')),
                ('inbound_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_subscription', to='crm.inboundrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
