# Generated by Django 5.0.14 on 2026-02-24 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_lead_interests_lead_objective_lead_preferred_channel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Point de vente')),
                ('channel', models.CharField(choices=[('grossiste', 'Grossiste'), ('detail', 'Détaillant'), ('ferme', 'Ferme'), ('institution', 'Institution'), ('autre', 'Autre')], default='detail', max_length=24, verbose_name='Canal')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ville')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Région')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('gps_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude')),
                ('gps_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=16, verbose_name='Statut')),
                ('notes', models.TextField(blank=True)),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlets', to='crm.customer', verbose_name='Distributeur')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.DateField(default=django.utils.timezone.now, verbose_name='Période')),
                ('expected_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantité prévue')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('confirme', 'Confirmé')], default='brouillon', max_length=16, verbose_name='Statut')),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='crm.customer', verbose_name='Client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='crm.product', verbose_name='Produit')),
                ('outlet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to='crm.outlet', verbose_name='Point de vente')),
            ],
            options={
                'ordering': ['-period'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='crm.outlet', verbose_name='Point de vente'),
        ),
        migrations.AddField(
            model_name='visitreport',
            name='outlet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='crm.outlet', verbose_name='Point de vente'),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Promotion')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date fin')),
                ('budget', models.PositiveIntegerField(default=0, verbose_name='Budget (FCFA)')),
                ('status', models.CharField(choices=[('planifie', 'Planifié'), ('actif', 'Actif'), ('termine', 'Terminé')], default='planifie', max_length=16, verbose_name='Statut')),
                ('notes', models.TextField(blank=True)),
                ('outlets', models.ManyToManyField(blank=True, related_name='promotions', to='crm.outlet')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.product', verbose_name='Produit')),
            ],
            options={
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Territoire')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Région')),
                ('notes', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territories', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='outlet',
            name='territory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outlets', to='crm.territory', verbose_name='Territoire'),
        ),
    ]
