# Generated by Django 5.0.14 on 2026-02-24 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_outlet_forecast_order_outlet_visitreport_outlet_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inboundrequest',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Première réponse'),
        ),
        migrations.AddField(
            model_name='inboundrequest',
            name='first_response_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA première réponse'),
        ),
        migrations.AddField(
            model_name='inboundrequest',
            name='priority',
            field=models.CharField(choices=[('faible', 'Faible'), ('normal', 'Normal'), ('eleve', 'Élevé'), ('urgent', 'Urgent')], default='normal', max_length=16, verbose_name='Priorité'),
        ),
        migrations.AddField(
            model_name='inboundrequest',
            name='resolution_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='SLA résolution'),
        ),
        migrations.AddField(
            model_name='inboundrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Résolu le'),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Score'),
        ),
        migrations.CreateModel(
            name='RoutingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('kind', models.CharField(blank=True, choices=[('lead', 'Lead web'), ('contact', 'Contact/Devis'), ('product', 'Produit'), ('career', 'Carrière'), ('newsletter', 'Newsletter')], max_length=24, verbose_name='Type de demande')),
                ('segment', models.CharField(blank=True, choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], max_length=24, verbose_name='Segment')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='Région/Ville')),
                ('channel_preference', models.CharField(blank=True, choices=[('appel', 'Appel'), ('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('visite', 'Visite terrain'), ('site', 'Site web'), ('referent', 'Référent/Partenaire')], max_length=24, verbose_name='Canal')),
                ('priority', models.PositiveIntegerField(default=100, verbose_name='Priorité')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_rules', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
    ]
