# Generated by Django 5.0.14 on 2026-02-25 00:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0008_inboundrequest_first_response_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='credit_exception_requested',
            field=models.BooleanField(default=False, verbose_name='Exception crédit'),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_pct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)'),
        ),
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Nom de la politique')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('min_order_total', models.PositiveIntegerField(default=0, verbose_name='Montant minimal commande (FCFA)')),
                ('min_discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Seuil remise (%)')),
                ('require_credit_exception', models.BooleanField(default=False, verbose_name='Exception crédit requise')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('approver_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_policies', to='auth.group', verbose_name='Groupe approbateur')),
                ('default_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_approval_policies', to=settings.AUTH_USER_MODEL, verbose_name='Approbateur par défaut')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('order', 'Commande'), ('opportunity', 'Opportunité'), ('support', 'Ticket support'), ('custom', 'Autre')], default='order', max_length=24, verbose_name='Entité')),
                ('object_id', models.PositiveIntegerField()),
                ('request_type', models.CharField(choices=[('discount', 'Remise'), ('credit', 'Exception crédit'), ('pricing', 'Exception tarifaire'), ('manual', 'Validation manuelle')], default='manual', max_length=24, verbose_name='Type de demande')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Refusé'), ('cancelled', 'Annulé')], default='pending', max_length=24, verbose_name='Statut')),
                ('reason', models.TextField(blank=True, verbose_name='Motif')),
                ('amount_fcfa', models.PositiveIntegerField(default=0, verbose_name='Montant (FCFA)')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)')),
                ('decision_note', models.TextField(blank=True, verbose_name='Commentaire décision')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='Demandé le')),
                ('decided_at', models.DateTimeField(blank=True, null=True, verbose_name='Décidé le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='contenttypes.contenttype')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_decided', to=settings.AUTH_USER_MODEL, verbose_name='Décidé par')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Demandé par')),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['entity_type', 'status'], name='crm_approva_entity__4b129d_idx'), models.Index(fields=['requested_at'], name='crm_approva_request_8798c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(choices=[('create', 'Création'), ('update', 'Mise à jour'), ('delete', 'Suppression'), ('status_change', 'Changement de statut'), ('approval', 'Validation'), ('sla', 'SLA/Escalade')], max_length=24, verbose_name='Événement')),
                ('source', models.CharField(choices=[('ui', 'Interface CRM'), ('api', 'API'), ('system', 'Système')], default='system', max_length=16, verbose_name='Source')),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='Objet')),
                ('actor_display', models.CharField(blank=True, max_length=120, verbose_name='Acteur (texte)')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='Request ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='User agent')),
                ('message', models.TextField(blank=True, verbose_name='Message')),
                ('changed_fields', models.JSONField(blank=True, default=list, verbose_name='Champs modifiés')),
                ('before_state', models.JSONField(blank=True, default=dict, verbose_name='Avant')),
                ('after_state', models.JSONField(blank=True, default=dict, verbose_name='Après')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='crm_audittr_created_80e5ba_idx'), models.Index(fields=['event', 'source'], name='crm_audittr_event_6a2970_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('inbound', 'Inbox'), ('lead', 'Lead'), ('customer', 'Client'), ('contact', 'Contact'), ('career', 'Carrière'), ('newsletter', 'Newsletter')], default='inbound', max_length=24, verbose_name='Source')),
                ('object_id', models.PositiveIntegerField()),
                ('issue_type', models.CharField(choices=[('missing_required', 'Champ requis manquant'), ('duplicate_potential', 'Doublon potentiel'), ('invalid_format', 'Format invalide'), ('inconsistent_data', 'Donnée incohérente'), ('consent_missing', 'Consentement manquant')], default='missing_required', max_length=40, verbose_name="Type d'anomalie")),
                ('severity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('critical', 'Critique')], default='medium', max_length=16, verbose_name='Sévérité')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('in_review', 'En revue'), ('resolved', 'Résolu'), ('ignored', 'Ignoré')], default='open', max_length=16, verbose_name='Statut')),
                ('fingerprint', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Empreinte')),
                ('message', models.TextField(verbose_name='Description')),
                ('suggested_action', models.TextField(blank=True, verbose_name='Action suggérée')),
                ('matched_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_quality_issues_assigned', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_quality_issues', to='contenttypes.contenttype')),
                ('matched_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_quality_matches', to='contenttypes.contenttype')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_quality_issues_resolved', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='crm_dataqua_status_075374_idx'), models.Index(fields=['source', 'issue_type'], name='crm_dataqua_source_e4e40f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SlaEscalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('inbound', 'Inbox'), ('support', 'Support'), ('task', 'Tâche')], default='inbound', max_length=24, verbose_name='Source SLA')),
                ('object_id', models.PositiveIntegerField()),
                ('escalation_level', models.CharField(choices=[('l1', 'Niveau 1'), ('l2', 'Niveau 2'), ('l3', 'Niveau 3')], default='l1', max_length=8, verbose_name='Niveau')),
                ('status', models.CharField(choices=[('open', 'Ouvert'), ('ack', 'Pris en charge'), ('resolved', 'Résolu')], default='open', max_length=16, verbose_name='Statut')),
                ('due_at', models.DateTimeField(verbose_name='Échéance SLA')),
                ('escalated_at', models.DateTimeField(auto_now_add=True, verbose_name='Escaladé le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('reason', models.CharField(max_length=255, verbose_name='Motif')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_escalations', to=settings.AUTH_USER_MODEL, verbose_name='Assigné à')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sla_escalations', to='contenttypes.contenttype')),
                ('notified_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sla_escalations', to='auth.group', verbose_name='Groupe notifié')),
            ],
            options={
                'ordering': ['-escalated_at'],
                'indexes': [models.Index(fields=['status', 'source_type', 'escalation_level'], name='crm_slaesca_status_551392_idx'), models.Index(fields=['due_at'], name='crm_slaesca_due_at_2eaf68_idx')],
            },
        ),
    ]
