# Generated by Django 5.0.14 on 2026-02-25 01:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('crm', '0009_order_credit_exception_requested_order_discount_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID public')),
                ('mfa_required', models.BooleanField(default=False, verbose_name='MFA requis')),
                ('force_password_reset', models.BooleanField(default=False, verbose_name='Forcer changement mot de passe')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Compte verrouillé')),
                ('failed_login_count', models.PositiveSmallIntegerField(default=0, verbose_name='Échecs de connexion')),
                ('last_password_rotation_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dernière rotation mot de passe')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dernière IP')),
                ('trusted_devices', models.JSONField(blank=True, default=list, verbose_name='Terminaux de confiance')),
                ('notes', models.TextField(blank=True, verbose_name='Notes sécurité')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('permanent', 'Permanent'), ('temporary', 'Temporaire'), ('scoped', 'Par dossier/projet')], default='permanent', max_length=16, verbose_name="Type d'assignation")),
                ('scope', models.CharField(choices=[('global', 'Global'), ('customer', 'Client'), ('opportunity', 'Opportunité'), ('order', 'Commande'), ('support', 'Support'), ('inbound', 'Inbox'), ('project', 'Projet'), ('custom', 'Autre')], default='global', max_length=24, verbose_name='Portée')),
                ('scope_reference', models.CharField(blank=True, max_length=255, verbose_name='Référence dossier/projet')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Valide à partir de')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name="Valide jusqu'au")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('reason', models.TextField(blank=True, verbose_name='Motif')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Révoqué le')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='contenttypes.contenttype')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_granted', to=settings.AUTH_USER_MODEL, verbose_name='Accordé par')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='auth.group', verbose_name='Rôle/Groupe')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments_revoked', to=settings.AUTH_USER_MODEL, verbose_name='Révoqué par')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active', 'scope'], name='crm_roleass_user_id_abda21_idx'), models.Index(fields=['group', 'assignment_type'], name='crm_roleass_group_i_c3b2e4_idx'), models.Index(fields=['valid_from', 'valid_to'], name='crm_roleass_valid_f_6a89e0_idx')],
            },
        ),
    ]
