# Generated by Django 5.0.14 on 2026-02-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_usersecurityprofile_roleassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleassignment',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('segment', 'Segment (espece)'), ('stage', 'Stade'), ('objective', 'Objectif'), ('region', 'Region'), ('customer', 'Client'), ('opportunity', 'Opportunité'), ('order', 'Commande'), ('support', 'Support'), ('inbound', 'Inbox'), ('project', 'Projet'), ('custom', 'Autre')], default='global', max_length=24, verbose_name='Portée'),
        ),
    ]
