# Generated by Django 5.0.14 on 2026-02-26 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_roleassignment_scope'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseConnector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('integration_type', models.CharField(choices=[('erp_compta', 'ERP/Compta'), ('telephony_whatsapp', 'Telephony/WhatsApp'), ('bi_analytics', 'BI/Analytics'), ('logistics_stock', 'Logistique/Stock')], max_length=32, verbose_name='Type integration')),
                ('direction', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=16, verbose_name='Direction')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('transport', models.CharField(choices=[('mock', 'Mock'), ('http', 'HTTP')], default='mock', max_length=16, verbose_name='Transport')),
                ('base_url', models.URLField(blank=True, verbose_name='Base URL')),
                ('auth_mode', models.CharField(choices=[('none', 'None'), ('api_key', 'API Key'), ('bearer', 'Bearer'), ('hmac', 'HMAC')], default='none', max_length=16, verbose_name='Mode auth')),
                ('auth_secret_id', models.CharField(blank=True, max_length=120, verbose_name='Secret ID')),
                ('timeout_seconds', models.PositiveIntegerField(default=10, verbose_name='Timeout (seconds)')),
                ('max_retries', models.PositiveSmallIntegerField(default=5, verbose_name='Max retries')),
                ('retry_backoff_seconds', models.PositiveIntegerField(default=30, verbose_name='Retry backoff (seconds)')),
                ('dlq_after_attempts', models.PositiveSmallIntegerField(default=5, verbose_name='DLQ after attempts')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['integration_type', 'active'], name='crm_enterpr_integra_1d84a0_idx'), models.Index(fields=['code', 'active'], name='crm_enterpr_code_b040fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseInboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_event_id', models.CharField(max_length=180, verbose_name='External event ID')),
                ('event_type', models.CharField(max_length=120, verbose_name='Event type')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed'), ('dead', 'Dead letter')], default='pending', max_length=16, verbose_name='Status')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed at')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Attempt count')),
                ('last_error', models.TextField(blank=True, verbose_name='Last error')),
                ('dedup_key', models.CharField(blank=True, max_length=180, verbose_name='Dedup key')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_events', to='crm.enterpriseconnector', verbose_name='Connector')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=64, verbose_name='Entity type')),
                ('entity_id', models.PositiveIntegerField(verbose_name='Entity ID')),
                ('event_type', models.CharField(max_length=120, verbose_name='Event type')),
                ('idempotency_key', models.CharField(max_length=180, verbose_name='Idempotency key')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('dead', 'Dead letter')], default='pending', max_length=16, verbose_name='Status')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Attempt count')),
                ('next_retry_at', models.DateTimeField(blank=True, null=True, verbose_name='Next retry at')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered at')),
                ('last_error', models.TextField(blank=True, verbose_name='Last error')),
                ('external_reference', models.CharField(blank=True, max_length=255, verbose_name='External reference')),
                ('request_id', models.CharField(blank=True, max_length=64, verbose_name='Request ID')),
                ('correlation_id', models.CharField(blank=True, max_length=64, verbose_name='Correlation ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='crm.enterpriseconnector', verbose_name='Connector')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseDeadLetterEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('outbox', 'Outbox'), ('inbox', 'Inbox')], max_length=16, verbose_name='Direction')),
                ('event_type', models.CharField(max_length=120, verbose_name='Event type')),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('attempt_count', models.PositiveIntegerField(default=0, verbose_name='Attempt count')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('connector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letters', to='crm.enterpriseconnector', verbose_name='Connector')),
                ('related_inbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letters', to='crm.enterpriseinboxevent', verbose_name='Related inbox')),
                ('related_outbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dead_letters', to='crm.enterpriseoutboxevent', verbose_name='Related outbox')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnterpriseFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=64, verbose_name='Entity type')),
                ('source_field', models.CharField(max_length=120, verbose_name='Source field')),
                ('target_field', models.CharField(max_length=120, verbose_name='Target field')),
                ('transform_rule', models.CharField(blank=True, max_length=64, verbose_name='Transform rule')),
                ('is_required', models.BooleanField(default=False, verbose_name='Required')),
                ('default_value', models.CharField(blank=True, max_length=255, verbose_name='Default value')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='crm.enterpriseconnector', verbose_name='Connector')),
            ],
            options={
                'ordering': ['connector', 'entity_type', 'version', 'source_field'],
                'indexes': [models.Index(fields=['connector', 'entity_type', 'active'], name='crm_enterpr_connect_d81953_idx'), models.Index(fields=['entity_type', 'target_field'], name='crm_enterpr_entity__bfb73b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='enterprisefieldmapping',
            constraint=models.UniqueConstraint(fields=('connector', 'entity_type', 'source_field', 'version'), name='uniq_connector_mapping_version'),
        ),
        migrations.AddIndex(
            model_name='enterpriseinboxevent',
            index=models.Index(fields=['status', 'created_at'], name='crm_enterpr_status_034b07_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseinboxevent',
            index=models.Index(fields=['connector', 'status'], name='crm_enterpr_connect_17f856_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseinboxevent',
            index=models.Index(fields=['dedup_key'], name='crm_enterpr_dedup_k_5b3618_idx'),
        ),
        migrations.AddConstraint(
            model_name='enterpriseinboxevent',
            constraint=models.UniqueConstraint(fields=('connector', 'external_event_id'), name='uniq_inbox_external_event_per_connector'),
        ),
        migrations.AddIndex(
            model_name='enterpriseoutboxevent',
            index=models.Index(fields=['status', 'next_retry_at'], name='crm_enterpr_status_ad4c12_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseoutboxevent',
            index=models.Index(fields=['connector', 'status'], name='crm_enterpr_connect_4fbc08_idx'),
        ),
        migrations.AddIndex(
            model_name='enterpriseoutboxevent',
            index=models.Index(fields=['entity_type', 'entity_id'], name='crm_enterpr_entity__f51e35_idx'),
        ),
        migrations.AddConstraint(
            model_name='enterpriseoutboxevent',
            constraint=models.UniqueConstraint(fields=('connector', 'idempotency_key'), name='uniq_outbox_idempotency_per_connector'),
        ),
        migrations.AddIndex(
            model_name='enterprisedeadletterevent',
            index=models.Index(fields=['direction', 'created_at'], name='crm_enterpr_directi_ee881e_idx'),
        ),
        migrations.AddIndex(
            model_name='enterprisedeadletterevent',
            index=models.Index(fields=['connector', 'direction'], name='crm_enterpr_connect_c68cb8_idx'),
        ),
    ]
