# Generated by Django 5.0.14 on 2026-03-05 00:21

import crm.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_enterpriseconnector_enterpriseinboxevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tax_ncc',
            field=models.CharField(blank=True, max_length=64, verbose_name='NCC'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_ntd',
            field=models.CharField(blank=True, max_length=64, verbose_name='NTD'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_rccm',
            field=models.CharField(blank=True, max_length=64, verbose_name='RCCM'),
        ),
        migrations.AddField(
            model_name='customer',
            name='tax_regime',
            field=models.CharField(blank=True, max_length=120, verbose_name='Régime fiscal'),
        ),
        migrations.AlterField(
            model_name='dataqualityissue',
            name='source',
            field=models.CharField(choices=[('inbound', 'Inbox'), ('lead', 'Lead'), ('customer', 'Client'), ('contact', 'Contact'), ('invoice', 'Facture'), ('career', 'Carrière'), ('newsletter', 'Newsletter')], default='inbound', max_length=24, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='enterpriseconnector',
            name='integration_type',
            field=models.CharField(choices=[('erp_compta', 'ERP/Compta'), ('telephony_whatsapp', 'Telephony/WhatsApp'), ('bi_analytics', 'BI/Analytics'), ('logistics_stock', 'Logistique/Stock'), ('fne_dgi', 'FNE/DGI')], max_length=32, verbose_name='Type integration'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(default=crm.models.default_invoice_number, max_length=32, unique=True, verbose_name='Numéro de facture')),
                ('source', models.CharField(choices=[('express', 'Vente express'), ('order', 'Depuis commande')], default='express', max_length=16, verbose_name='Source')),
                ('status', models.CharField(choices=[('brouillon', 'Brouillon'), ('emise', 'Émise'), ('partiellement_payee', 'Partiellement payée'), ('payee', 'Payée'), ('annulee', 'Annulée')], default='brouillon', max_length=24, verbose_name='Statut')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('issued_at', models.DateTimeField(blank=True, null=True, verbose_name='Émise le')),
                ('currency', models.CharField(default='FCFA', max_length=8, verbose_name='Devise')),
                ('subtotal_amount', models.PositiveIntegerField(default=0, verbose_name='Sous-total (FCFA)')),
                ('discount_amount', models.PositiveIntegerField(default=0, verbose_name='Remise totale (FCFA)')),
                ('tax_amount', models.PositiveIntegerField(default=0, verbose_name='Taxes (FCFA)')),
                ('total_amount', models.PositiveIntegerField(default=0, verbose_name='Total TTC (FCFA)')),
                ('paid_amount', models.PositiveIntegerField(default=0, verbose_name='Montant payé (FCFA)')),
                ('payment_method', models.CharField(choices=[('non_renseigne', 'Non renseigné'), ('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('credit', 'Crédit')], default='non_renseigne', max_length=24, verbose_name='Mode de paiement')),
                ('payment_reference', models.CharField(blank=True, max_length=255, verbose_name='Référence paiement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('fne_required', models.BooleanField(default=True, verbose_name='Certification FNE requise')),
                ('fne_status', models.CharField(choices=[('not_sent', 'Non envoyé'), ('pending', 'En attente'), ('certified', 'Certifiée'), ('rejected', 'Rejetée'), ('not_required', 'Non requis')], default='not_sent', max_length=24, verbose_name='Statut FNE')),
                ('fne_reference', models.CharField(blank=True, max_length=255, verbose_name='Référence FNE')),
                ('fne_certified_at', models.DateTimeField(blank=True, null=True, verbose_name='Certifiée FNE le')),
                ('fne_last_error', models.TextField(blank=True, verbose_name='Dernière erreur FNE')),
                ('fne_payload', models.JSONField(blank=True, default=dict, verbose_name='Payload FNE')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='crm.customer', verbose_name='Client')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.order', verbose_name='Commande source')),
                ('sales_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Commercial responsable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('unit_price', models.PositiveIntegerField(default=0, verbose_name='Prix unitaire (FCFA)')),
                ('discount_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Remise (%)')),
                ('tax_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taxe (%)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.invoice', verbose_name='Facture')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status', 'created_at'], name='crm_invoice_status_39df83_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['fne_status', 'created_at'], name='crm_invoice_fne_sta_31c862_idx'),
        ),
    ]
