# Generated by Django 5.0.14 on 2026-03-05 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_customer_tax_ncc_customer_tax_ntd_customer_tax_rccm_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name="Motif d'avoir/annulation"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='nature',
            field=models.CharField(choices=[('standard', 'Facture'), ('credit_note', 'Avoir')], default='standard', max_length=16, verbose_name='Nature'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='crm.invoice', verbose_name="Facture d'origine"),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['nature', 'created_at'], name='crm_invoice_nature_da6e20_idx'),
        ),
    ]
