# Generated by Django 5.0.14 on 2026-03-05 01:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_invoice_cancellation_reason_invoice_nature_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.PositiveIntegerField(verbose_name='Montant payé (FCFA)')),
                ('payment_method', models.CharField(choices=[('non_renseigne', 'Non renseigné'), ('especes', 'Espèces'), ('mobile_money', 'Mobile Money'), ('virement', 'Virement'), ('cheque', 'Chèque'), ('credit', 'Crédit')], default='non_renseigne', max_length=24, verbose_name='Mode de paiement')),
                ('payment_reference', models.CharField(blank=True, max_length=255, verbose_name='Référence paiement')),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Payé le')),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('integration', 'Flux integration')], default='manual', max_length=16, verbose_name='Source')),
                ('source_connector', models.CharField(blank=True, max_length=64, verbose_name='Code connecteur source')),
                ('source_event_id', models.CharField(blank=True, max_length=180, null=True, verbose_name='ID événement source')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='crm.invoice', verbose_name='Facture')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_invoice_payments', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'ordering': ['-paid_at', '-created_at'],
                'indexes': [models.Index(fields=['invoice', 'paid_at'], name='crm_invoice_invoice_6338b8_idx'), models.Index(fields=['source', 'source_connector', 'source_event_id'], name='crm_invoice_source_1000f5_idx')],
            },
        ),
    ]
