# Generated by Django 5.0.14 on 2026-06-22 20:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_invoicepayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_stock_alert',
            field=models.PositiveIntegerField(default=0, help_text="En dessous de ce stock disponible, le produit est signalé en rupture/alerte. 0 = pas d'alerte.", verbose_name="Seuil d'alerte stock"),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='Code')),
                ('warehouse_type', models.CharField(choices=[('usine', 'Usine / Production'), ('depot', 'Dépôt central'), ('magasin', 'Magasin / Point de vente'), ('autre', 'Autre')], default='depot', max_length=16, verbose_name='Type')),
                ('city', models.CharField(blank=True, max_length=120, verbose_name='Ville')),
                ('region', models.CharField(blank=True, choices=[('Abidjan', 'Abidjan'), ('Bouaké', 'Bouaké'), ('Yamoussoukro', 'Yamoussoukro'), ('San-Pédro', 'San-Pédro'), ('Korhogo', 'Korhogo'), ('Daloa', 'Daloa'), ('Man', 'Man'), ('Gagnoa', 'Gagnoa'), ('Autre', 'Autre')], max_length=120, verbose_name='Région')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_warehouses', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='crm.territory', verbose_name='Territoire')),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lot_code', models.CharField(max_length=64, verbose_name='N° de lot')),
                ('unit', models.CharField(choices=[('sac', 'Sac'), ('kg', 'Kilogramme'), ('tonne', 'Tonne'), ('litre', 'Litre'), ('carton', 'Carton'), ('unite', 'Unité')], default='sac', max_length=12, verbose_name='Unité')),
                ('quantity_initial', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité initiale')),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Quantité en stock')),
                ('unit_cost', models.PositiveIntegerField(default=0, verbose_name='Coût unitaire (FCFA)')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Date de fabrication')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Date de péremption (DLUO)')),
                ('status', models.CharField(choices=[('disponible', 'Disponible'), ('reserve', 'Réservé'), ('quarantaine', 'Quarantaine'), ('bloque', 'Bloqué'), ('epuise', 'Épuisé')], default='disponible', max_length=16, verbose_name='Statut')),
                ('supplier_reference', models.CharField(blank=True, max_length=120, verbose_name='Référence fournisseur/OF')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='crm.product', verbose_name='Produit')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='crm.warehouse', verbose_name='Entrepôt')),
            ],
            options={
                'verbose_name': 'Lot de stock',
                'verbose_name_plural': 'Lots de stock',
                'ordering': ['expiry_date', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('entree', 'Entrée (production / achat)'), ('sortie', 'Sortie (vente / livraison)'), ('ajustement', "Ajustement d'inventaire"), ('perte', 'Perte / casse / péremption'), ('transfert_out', 'Transfert sortant'), ('transfert_in', 'Transfert entrant')], max_length=16, verbose_name='Type de mouvement')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Quantité')),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Solde après mouvement')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motif')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date du mouvement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='crm.invoice', verbose_name='Facture liée')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='crm.stocklot', verbose_name='Lot')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='crm.order', verbose_name='Commande liée')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('counterpart_warehouse', models.ForeignKey(blank=True, help_text="Pour les transferts : entrepôt d'origine ou de destination.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='crm.warehouse', verbose_name='Entrepôt de contrepartie')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-occurred_at', '-created_at'],
                'indexes': [models.Index(fields=['lot', 'occurred_at'], name='crm_stockmo_lot_id_4c815d_idx'), models.Index(fields=['movement_type', 'occurred_at'], name='crm_stockmo_movemen_c6c7ec_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['status', 'expiry_date'], name='crm_stocklo_status_a862d2_idx'),
        ),
        migrations.AddIndex(
            model_name='stocklot',
            index=models.Index(fields=['product', 'warehouse'], name='crm_stocklo_product_a2bd95_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklot',
            constraint=models.UniqueConstraint(fields=('product', 'warehouse', 'lot_code'), name='unique_lot_per_product_warehouse'),
        ),
    ]
