# Generated by Django 5.0.14 on 2026-06-22 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_product_min_stock_alert_warehouse_stocklot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_hold',
            field=models.BooleanField(default=False, help_text='Si coché, le client est signalé en blocage : ne plus livrer à crédit.', verbose_name='Compte bloqué (crédit)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.PositiveIntegerField(default=0, help_text="Montant maximum d'encours autorisé pour ce client. 0 = pas de crédit accordé.", verbose_name='Plafond de crédit (FCFA)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='payment_terms_days',
            field=models.PositiveIntegerField(default=0, help_text='Délai accordé pour régler une facture (ex. 30 jours). 0 = paiement comptant.', verbose_name='Délai de paiement (jours)'),
        ),
    ]
