# Generated by Django 5.0.14 on 2026-06-22 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0017_customer_credit_hold_customer_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_price',
            field=models.PositiveIntegerField(default=0, help_text="Coût d'achat/production unitaire. Sert au calcul de la marge.", verbose_name='Coût de revient (FCFA)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix de vente de référence (FCFA)'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_type', models.CharField(choices=[('eleveur', 'Éleveur'), ('distributeur', 'Distributeur'), ('integrateur', 'Intégrateur'), ('veterinaire', 'Vétérinaire'), ('revendeur', 'Revendeur'), ('industrie', 'Industrie/Transformateur'), ('autre', 'Autre')], max_length=24, verbose_name='Type de client')),
                ('unit_price', models.PositiveIntegerField(default=0, verbose_name='Prix unitaire (FCFA)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_prices', to='crm.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Tarif par segment',
                'verbose_name_plural': 'Tarifs par segment',
                'ordering': ['product__name', 'customer_type'],
            },
        ),
        migrations.AddConstraint(
            model_name='productprice',
            constraint=models.UniqueConstraint(fields=('product', 'customer_type'), name='unique_price_per_product_customer_type'),
        ),
    ]
