# Generated by Django 5.0.14 on 2026-06-22 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_product_cost_price_alter_product_unit_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('segment', models.CharField(blank=True, choices=[('volailles', 'Volailles'), ('porcins', 'Porcs'), ('poissons', 'Poissons'), ('biosecurite', 'Biosécurité'), ('multi', 'Multi-espèces')], max_length=24, verbose_name='Espèce (optionnel)')),
                ('period_year', models.PositiveIntegerField(verbose_name='Année')),
                ('period_month', models.PositiveSmallIntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('target_amount', models.PositiveIntegerField(default=0, verbose_name='Objectif CA (FCFA)')),
                ('target_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Objectif volume')),
                ('commission_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de commission (%)')),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('clos', 'Clôturé')], default='actif', max_length=12, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_targets', to=settings.AUTH_USER_MODEL, verbose_name='Commercial')),
                ('territory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_targets', to='crm.territory', verbose_name='Territoire')),
            ],
            options={
                'verbose_name': 'Objectif commercial',
                'verbose_name_plural': 'Objectifs commerciaux',
                'ordering': ['-period_year', '-period_month', 'owner__username'],
                'indexes': [models.Index(fields=['period_year', 'period_month'], name='crm_salesta_period__beafd0_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='salestarget',
            constraint=models.UniqueConstraint(fields=('owner', 'period_year', 'period_month', 'segment'), name='unique_target_per_owner_period_segment'),
        ),
    ]
